version: 2.1

orbs:
  maven: circleci/maven@0.0.12
  azure-acr: circleci/azure-acr@0.2.0

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
      - azure-acr/build-and-push-image:
          requires:
            - maven/test
          login-server-name: esgijeeproject.azurecr.io
          registry-name: esgiJeeProject
          repo: basket-jee-app
          tag: $CIRCLE_TAG