version: 2.1
orbs:
  maven: circleci/maven@0.0.12
  aws-ecr: circleci/aws-ecr@6.5.0
  aws-ecs: circleci/aws-ecs@0.0.10
workflows:
  maven_test:
    jobs:
      - maven/test:
          filters:
            branches:
              only:
                - master
      - aws-ecr/build-and-push-image:
          requires:
            - maven/test
          account-url: AWS_ECR_ACCOUNT_URL
          repo: '${MY_APP_PREFIX}'
          region: AWS_REGION
          tag: '${CIRCLE_SHA1},latest'
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          family: '${MY_APP_PREFIX}'
          cluster-name: '${MY_APP_PREFIX}'
          container-image-name-updates: 'container=${MY_APP_PREFIX},tag=${CIRCLE_SHA1}'