version: 2.1
jobs:
  build:
    executor: docker/docker
    parameters:
      image:
        type: string
      registry:
        type: string
    steps:
      - setup_remote_docker
      - checkout
      - azure-cli/install
      - azure-cli/login-with-service-principal
      - azure-acr/acr-login
      - docker/build:
          image: << parameters.image >>
          registry: << parameters.registry >>
      - docker/push:
          image: << parameters.image >>
          registry: << parameters.registry >>

orbs:
  maven: circleci/maven@0.0.12
  azure-cli: circleci/azure-cli@1.1.0
  azure-acr: circleci/azure-acr@0.2.0
  docker: circleci/docker@1.0.1
workflows:
  maven_test:
    jobs:
      - maven/test
      - build:
          requires:
            - maven/test
          image: basket-jee-app
          registry: esgijeeproject.azurecr.io